# Generated by Django 2.1.1 on 2018-11-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=20)),
                ('Time', models.CharField(max_length=50)),
                ('Reading', models.CharField(max_length=20)),
                ('Comment', models.CharField(max_length=20)),
                ('Classify', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=10000)),
            ],
        ),
    ]
